# Generated by Django 4.2.27 on 2026-02-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
